In [2]:
import numpy as np

In [4]:
lst=[1,2,3,4]
arr=np.array(lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [8]:
## 4, means one dimensional element(one column or one row)
arr1=np.array([[1,2,3],[4,5,6]])


In [9]:
arr1.shape

(2, 3)

In [10]:
## 2,3 means 2 rows and 3 columns(2 dimensional)


In [11]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [13]:
#tuple conversion
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [17]:
arr2=np.array({"name":"rahul","class":"ds","rollnumber":45})

In [18]:
arr2.dtype

dtype('O')

In [19]:
# array from scratch
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
np.arange(1,10,2).shape

(5,)

In [21]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [22]:
np.arange(1,20,3)##(1 is the minimum value,20 is the maximum value,3 is the steps)


array([ 1,  4,  7, 10, 13, 16, 19])

In [25]:
np.arange(1,20,3).reshape(7,1)


array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16],
       [19]])

In [27]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [29]:
np.arange(1,20,2).reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [30]:
np.arange(1,20,2).reshape(1,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [31]:
np.arange(1,20,2).reshape(10,1)

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

In [32]:
np.arange(1,20,2).reshape(10,1).shape

(10, 1)

In [33]:
np.array(range(1,10,1))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
##array in reverse order
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [35]:
## if we want 40 elements between 1 to 20
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [36]:
## zeros in the form arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones((2,5))#(by default numpy gives yu array in floating number only)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.ones((5,2,8))##(2,8 represents the number of rows and columns and 5 represents the number of times the rows and columns will be repeated)

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [43]:
##broadcasting(applying to every element)
#arithematic operation
5+np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [44]:
#identity matrix(diagonal values are 1 and the other 0)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
##how to generate some random values in array
print("random number generation(uniform distribution)")
np.random.rand(2,3)

random number generation(uniform distribution)


array([[0.48331256, 0.99477108, 0.13010494],
       [0.92385907, 0.80098931, 0.72224604]])

In [48]:
#random number generation following a normal distribution
print("random number following a normal distribution with mean=0 and std=1")
print(np.random.randn(5,6))

random number following a normal distribution with mean=0 and std=1
[[ 0.98445753 -0.4816859   0.44375569  0.23162408  0.30512028  1.17565955]
 [-1.62805104  0.12033168  1.33181986 -0.49054333  2.44013116  0.27742673]
 [-0.34887708 -2.1176875   0.55748838 -1.62061208  0.29067742  0.74960805]
 [-0.26200898  0.48035921  1.28873402  0.63775477 -1.17516995 -0.11678798]
 [-0.88051759  0.19740607 -1.4000553   0.77134873 -0.35493616 -0.44950261]]


In [49]:
np.random.randint(1,100,50)

array([50, 64, 49, 49, 23,  2, 14, 63, 46, 87, 21, 11, 48, 87, 48, 90, 55,
       21, 63, 26, 37, 24, 95, 46, 28, 60, 37, 78, 63, 30, 60, 82,  3, 39,
       52, 90, 96, 81, 41, 23, 92, 89, 28, 73, 52, 27, 45, 33,  5, 44])

In [50]:
np.random.randint(1,100,(4,4))

array([[68, 86, 76, 84],
       [ 2, 44, 11, 29],
       [22, 91, 27, 54],
       [23, 60, 91, 35]])

In [54]:
##slicing
arr=np.arange(0,11)

In [55]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [58]:
arr[2:-4]

array([2, 3, 4, 5, 6])

In [59]:
#negative indexing
arr[-1:7:-1]

array([10,  9,  8])

In [66]:
arr1=np.random.randint(2,100,20).reshape(5,4)
arr1

array([[26, 84, 10, 16],
       [11, 93, 24, 84],
       [71, 45, 76, 15],
       [90, 23, 69, 31],
       [83, 77, 40, 77]])

In [72]:
arr1[0:3,0:3]# slicing will work different for rows and different for columns


array([[26, 84, 10],
       [11, 93, 24],
       [71, 45, 76]])

In [103]:
71,90,15,31
arr1[2:4,[2:4,3:4]]



SyntaxError: invalid syntax (175124222.py, line 2)

In [104]:
#universal operations
#shape of both the arrays should be same
arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))


In [105]:
arr1*arr2

array([[1840,  340, 2745],
       [1215,  122, 6162],
       [3185, 6188,  781]])

In [106]:
arr1 + arr2

array([[103,  73, 106],
       [ 96,  63, 157],
       [114, 159,  82]])

In [107]:
arr1/arr2

array([[3.47826087, 0.07352941, 0.73770492],
       [0.18518519, 0.03278689, 0.98734177],
       [0.75384615, 0.74725275, 0.15492958]])

In [109]:
arr1=np.arange(1,10)

In [110]:
arr1[2:]=1000

In [111]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])